# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: Build Extension Pack

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - master
      - version*

  pull_request:
    branches-ignore:
      - 'tmp_*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
#concurrency:
#  group: "pages"
#cancel-in-progress: false

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: list files
        run: "ls -la"
      - name: Call Script
        run: "bash scripts/packExtension.sh"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./export/toggleAudio@blackeyeprojects.de.shell-extension.zip

